---

- include: install.deb.yml
  when: ansible_os_family == 'Debian'
  tags: [jenkins, jenkins-install]

- include: configure.yml
  tags: [jenkins, jenkins-configure]

- include: plugins.yml
  when: jenkins_plugins
  tags: [jenkins, jenkins-plugins]

- include: ssh.yml
  tags: [jenkins, jenkins-ssh]

- include: jobs.yml
  when: jenkins_jobs
  tags: [jenkins, jenkins-jobs]

- include: auth.yml
  when: jenkins_proxy_auth
  tags: [jenkins, jenkins-auth]

- include: nginx.yml
  when: jenkins_proxy == "nginx"
  tags: [jenkins, jenkins-nginx]

- include: apache.yml
  when: jenkins_proxy == "apache"
  tags: [jenkins, jenkins-apache]
